import React from 'react';

import "./Blog.css";

function Blog() {
    return (
        <div>
            <div className="blog">
                <article>
                    <h2>September 2022</h2>
                    <p>September was a hell of a month, with school back in action I was having fun meeting new people, studying nursing, and getting ready for a half a marathon. Regarding the marathon, I was supposed to run it because I wanted to look cool for a girl, but she bailed on me. So, I ran a half marathon by myself at a 4:50min/km pace by myself. To be honest it was entertaining running with all the people. I didn’t expect to be running straight out of the gate with a 3 min/km pace and was surprised 5 mins afterwards when I was already gasping for air like a fish that stayed on land too long. I toned down my speed to 4:50min/km and held it as long as possible before suffering. I decided after the race to complete 2 marathons a year. So yeah, on top of bike races I now have marathons to keep everything fresh. Grades are pretty good with me not having to work. So all in all, everything is OK.</p>
                    <h2>August 2022</h2>
                    <p>This august was really fun. I decided to switch campuses and go back to Sherbrooke city and volunteer for the initiation to get to know people. Met a lot of new people that were amicable and very inviting. Got to meet some people in my classes that seem to take care of me like I was their little brother. Can’t say I don’t like the attention, but it was weird having people that don’t know me want to take care of me. Anyways, I don’t have my appartement yet, but I’ll just wait awhile.</p>
                    <p>The cool thing about Sherbrooke is that the mountain is legal and free to go biking, so I don’t need to use the car to go mountain biking. The 5km of pre-ride is pretty annoying though, but its ok at the end of the day.
                    really got into SQL and python, and its getting there, I know how to code better and its honestly a nice skill to have.
                    </p>
                    <h2>June 2022</h2>
                    <p>I still haven’t started the new job in Quebec yet. But I did have time to bike on the road and on the mountains. I met a lot of people, and all of them taught me how to ride more efficiently. On the road, a veteran taught me how to lead and use hand signals to control group tempo. On the mountains, I had someone teach me how to adapt to the local trails. He did say that my travel was a bit under par, but it shouldn’t stop me from riding. </p>
                    <p>I got back into coding more specifically python. But I am at the beginning and don’t seem to be doing anything impressive. For the moment I think my react skills are more impressive, but I am kind of legacy, because I know a new version of react came out and I have yet to learn the subtleties.</p>
                    <h2>May 2022</h2>
                    <p>This month was my last month of exams this year. And I got my bike way earlier then I thought. Didn’t have time to use it since I was working and IT GOD DAMNED RAINED THE WHOLE WEEK, I GOT IT. Anyways let’s circle back to my work/school life. I did my last exam in mental in community. I was worried sick because my last grade was 52%. So, I made sure to study my ass off and got 80% on the next exam which averaged to around 65%. Still passed my boy. With that out of the way I can get ready to start planning my summer in Quebec. The forecast is a vintage 6 room apartment with one roommate and that’s it. Honestly, I would go without the roommate, but 6 rooms are pretty bad-ass. </p>
                    <p> you can see that I am more relaxed with my writing because I write more and keep most subjects simple. That’s all for this month and ill see you soon my BRAS. </p>
                    <h2>April 2022</h2>
                    <p>April was a hell of a month. Got the chance to work in maternity care and pediatric care. Honestly, I really like both. I do prefer pediatrics because I get to take care of kids. It is not that I hate taking care of moms, but its because its slightly more varied. Maternity is almost always the same thing, mom, and baby, but with pediatrics I get a bit more variations in the sicknesses and situations that the family present themselves in. I do not like having a set-in stone routine, so pediatrics is more my flavour of the day. I finally got my bike back in riding shape and I am already starting to rewatch videos on how to ride and do some crazy stuff. Lets just hope I do not hurt myself to much by going all out xD. My summer is starting to take shape with me wanting to get back into coding, reading articles and finally cycling as much as I can. I do miss road riding, but its OKAY, CUZ I ORDERED A NEW BIKE.</p>
                    <h2>March 2022</h2>
                    <p>BACK ON TIME BBY. The beginning of march was okay, but towards the end I lived this existential crisis where I am asking myself am I making enough money. I am in university working part time, so my revenue is lower than what it should be, Yet I am still making a decent amount. On top of that my dad with his semi-obsession for money is getting on my nerves. But I understand he is worried. TLDR beginning of the month I was okay, now I am feeling more like meh.</p>
                    <h2>February 2022</h2>
                    <p>I am writing this pretty late. I feel like February was a while ago because I am in April right now. Its insane how I forgot to write about this and now I am totally out of ideas. Ill just say fuck it.</p>
                    <h2>January 2022</h2>
                    <p>Well then, let`s start with the obvious new year, new me. Still in school but halfway there now. I do not have much to do except studying, working, and exercising. The maternity lessons are moving way to fast for my liking, but I understand that we must get this over with ASAP for the internships. Work is okay, but with deconfinement the cases are going up again. It iss bound to happen every time. Anyways going to keep my head down and going to keep the grind on.</p>
                    <h2>December 2021</h2>
                    <p>The beginning of the month was ok. I do have to admit that I was still shaken by my exam from last month. I was a bit stressed continuing with work and school. School front I had an internship that was moving very fast and 2 medication incidents that caught me off guard. On the work front, Covid patients are steadily coming back into rotation. Then out of nowhere, middle of the month arrives, and we have 22/30 beds with Covid. Another surprise as we could say. But this time around, symptoms were less pronounced. If I had to give a number 3 out of 22 patients were in a rough state with department needing help from breathing therapist. According to my coworkers January is going to be a hell of a month with Christmas and new year eve being the perfect excuse for people to meet up.</p>
                    <h2>November 2021</h2>
                    <p>Meh, School fucked me up with a bad exam, still passed the class, but DAMN, I got fucked xD. Maybe I need to study a bit more next semester.</p>
                    <h2>October 2021</h2>
                    <p>Applied to a different hospital for the beginning of next summer. Got a response back from Quebec city which is cool. My priority right now is just investing, school and sports. I kind of left coding and writing on the side because things are hectic at school right now. But after my exam on the 11th, I should be able to get some more free time again. Maybe ill get back to coding, and writing.  </p>
                    <h2>September 2021</h2>
                    <p>I guess covid never really left 😕. Part of the oncology unit is becoming a covid unit again because we have negative pressure rooms. I am seeing an annoying trend unfortunately. Most patients are unvaccinated and around their thirties. At least they are understanding and collaborating, so I don’t need to work with some anti-vaxxer attitude. I realized most of them are very attentive to what I have to say, mainly because I answer their question and explain how most patients with Covid are treated on our unit. Anyways, I am having fun but staying focused for school is harder than I thought because I must study even if I am feeling tired. </p>
                    <h2>August 2021</h2>
                    <p>The infamous back to school season 😑. Honestly Its going well for the moment, I had time to check the school cursus and It is pretty good for my situation. A few team projects, a few exams solo and a lot of homework to do. The good thing is I can do everything at my leisure, the bad thing is if I fall behind, I am going to be in a really bad situation. I am continuing my job as a nursing intern in oncology by working 20h per 14days. </p>
                    <h2>July 2021</h2>
                    <p>
                    So, I don’t know how I feel about my unit lol. The team is cool, the patients are well taken of and mostly appropriate for our type of care and I genuinely like working at night. The tempo is a lot slower now since I know how the unit works. There is also the fact that I have the same 11 patients for 10 days straight. I make a work plan the first day and I can keep it for the next 11 days and tweak some stuff. If a patient gets discharged, I just add a new worksheet. I never thought I would be able to make a routine as a nurse, but I can. I try not to follow it, because some people require more care than others, but its so easy. I even decided to read a book atomic habits to learn how not to stick to my bad habits. 
                    </p>
                    <h2>June 2021</h2>
                    <p>
                    First real month working as a nurse, and it’s been fun. Learning how a unit works, meeting new people and getting orientated on how to work as a team. I do not really have time to get back into my mountain biking habit since I don`t have a car anymore. Told myself I was going to transition to gravel biking to keep my fitness up, but I guess I will just hit up the pool instead since I love swimming. (FIY: I never did hit the pool during June. It was not out of laziness, but mostly because I couldn’t find a public pool that opened when I finished working)
                    </p>
                    <h2>May 2021</h2>
                    <p>I think this month was the month I went most fuck it in my life. I was tired physically and mentally and with my funds coming a bit short I kind of felt a bit stressed. Its not that I couldn`t pay my obligations like rent and etc…  There is also the fact that most of my money is in stocks right now sooo I am really trying not to withdraw my money just to feel better about my bank account number. It`s just annoying to have a sub 2K bank account when you dream about a 6K bike. On the upside I am finally starting at the hospital, and I am psyched to get started. I am just going to have to tell my parents about my college.</p>
                    <h2>April 2021</h2>
                    <p>Honestly, I am just going to keep it short this time. I am tired of school all I want to do is just start my job at the hospital and chill. But I know deep inside of me that now is not the time to chill. I am still young, and I can still keep pushing. I settled on just doing enough to feel like I am still productive, but not enough to want to absolutely want to not give a god damn shit about life.  So yeah, I am having a lot of fun right now xD.</p>
                    <h2>March 2021</h2>
                    <p>So, this month I had a bit of an unprecedented month. Starting to help out at the hospital again so I took 2 days of my job. School is doing okay, but I need to put in more effort, I let go for like one week and now I feel like I am absolutely lost.</p>
                    <p>On the upside I finally started getting my bike parts for this season. Gonna go through with turning my bike into a mini-enduro rig. Got most of the parts that I need, now I`ll just play around with the stuff that I have. And keep ordering parts until July. Slowly but surely, I can build myself a cool rig. I plan on buying a gravel bike later too so that is going to be fun.</p>
                    <p>Finally, I do regret spending less time talking with my family, but when I get my final dose for the vaccine I`ll start trying to talk with them a lot. </p>
                    <h2>February 2021</h2>
                    <p>School was super easy this month. I cannot really put my finger on it, but I think universities made the curriculum easier to compensate because of reduced academic support. Last year, we could have gone to the library, used all the campus labs. This year all we can do is use our computers and the power of the internet. I was able to work a bit on my website and implement things like the automatic header close function and start adding new content. I got a 360 down on my snowboard, I WAS SUPER STOKED. I think I can start going for bigger stuff on my snowboard. Unfortunately, snow is starting to melt to I do not have a lot of time. </p>
                    <h2>January 2021</h2>
                    <p>Well, we survived a year lol. I took time to read my whole blog and I realized that last year I did more then I remember. I smile when I read this because I realized for how much people said 2020 was bad, I still had a lot of fun doing my thing and learning to do code, getting back in school and working on bikes. I have a job lined up in 3 months now at a hospital in a beautiful place. All I need to do now is endure 3 more months and I am going have the time of my life. Going to knock on some wood and get back to work.</p>
                    <h2>December 2020</h2>
                    <p>So final month of the year, it has been a year since I started doing monthly blog. I am happy I stuck with this project. I saw how I was at the beginning of the year and how I am doing now. I can confidently say that I grew this year and learned a lot more then I though. As I reread this, I realize all the details that I missed in the month. I can also see that I sugar-coated a few stories in this page LMAO. I am still working on being transparent even with things that are hard to say. Even now it feels like I can be truthful to myself, but I can`t lie to my family. I still have a lot of things that I plan to do. For the moment, I am going to get back on coding and wait for my ER job to start in May. </p>
                    <br/><b>Lesson of the Year</b>
                    <p>I realized that I tend to underplay a lot off stuff. As I reread this blog of 2020 the small details that I thought didn`t matter seem to be more important now in the future. Guess that`s my lesson this year, pay attention to the small details.</p>
                    <b>Resolutions</b>
                    <p>More Biking, More Nursing, More volunteering, and more Coding. </p>
                    <h2>November 2020</h2>
                    <p>November went by faster then I thought. I got around buying new snowboarding gear this month. I wasn’t ready for the expenses for my dads car though. I SPENT 1K on winter tires. On the upside, I did do research on them, and I know for a fact that they will last around 5-10 years easily. I started my interships at the hospital again. I am in geriatry in CHSLD chevalier de levi and I realized that there is a lot for me to relearn. Most notably is the approach with older people. I am someone who likes to move fast and taking my time feels really slow. In an older population going slower allows them to understand what you are doing and get more cooperation.</p>
                    <h2>October 2020</h2>
                    <p>Its getting better. Had some pretty good exam in school so I am happy about that. Started calling and doing my registrations for my jobs. Got a callback from CHUQ in order to go work on the 31th of may 2021. Honestly I AM SOOO EXCITED FOR THIS. It would really be cool to visit a city and go work in Quebec next to SDM and Charlevoix. I do have to admit I am kinda scare about the last checks that I need to do like sending my Immatriculation. I Dunno, I feel like because I really want to get this job the pressure is up. </p>
                    <h2>September 2020</h2>
                    <p>Honestly with school picking up and me getting less time at the job It feels like I am still working full time. The only difference is that I am studying a lot more at home. I do admit I am having a few troubles with this because I tend to be able to navigate towards youtube in one click. And pair that with half a year of studying online and using youtube vids to learn how to code react and you get a guy that instinctly goes towards youtube. But apart from that its going pretty good. My income with work is sufficient, nothing to be happy about but it lets me keep a bit of income in the side for stuff I want to buy like my bike next year. </p>
                    <h2>August 2020</h2>
                    <p>Yo, august wen in a flash. I was happy with my work and getting into enduro racing. My placement on the ladder has improved, I am able to get top 5 in mens elite. But that’s still a far from men’s pro. I realized on multiple race day that I was riding with the wrong bike. YUP, I only have 120 mm of travel front and rear against people with 170mm with slacker headtubes. The result of that is that my bike is a lot more twitchier at high speeds then them. And because of that I might feel like I am less composed when I am going fast.School started again, Online for the most part with a few classes physical in order to review nursing techniques and approach. </p>
                    <p>In the shop we had a problem with the port so we didn’t receive any shipment for like 3 weeks. We are out of bikes and so my job went from bike mechanic to warehouse employee I guess. Means I gotta work on receive, treating and classing packages in the meantime that we get bikes.</p>
                    <h2>July 2020</h2>
                    <p>This month I had my first bike race in ever. I live in Montreal but I had to drive all the way to Herbert-Ville in order to race. I did what people call an enduro race. An Enduro MTB race is about 25-30km and I am only timed on my descent. Yup its more time trial then anything. That’s also one of the reason why I can race during the pandemic. We all go down the race courses one at a time. That means we respect the sanitary measuires that are forced by the government. How did I fare? Bad lmao. I finished 6/8 with a total time of 17minutes on 4 stages. My friend checked my time and told me I had the best times on the first 3 stages then I threw the towel on the 4 stages with a 6minute finish on that one only. I have a few excuses to justify my placement on the ladder. But I am over excuses this year, all I am gonna do is get better and work on my weaknesses like commiting to big jumps and also plowing through rock gardens. </p>
                    <p>On the work side, its getting more complicated because we are opening more stores and our demand is starting to explode. We are also expanding our services so we have to learn how to take care of more stuff.</p>
                    <p>Personal side, kinda complicated I want to tell my parents I am moving out, but I fear they might be super against the idea. Ill tell them soon. </p>
                    <h2>June 2020</h2>
                    <p>
                    Second month as a bike Mechanic and I have the feeling that people are buying even more bikes. We went out of stock for awhile but then we got bikes again. I have the feeling that people ordered even more bikes this month.  On the good side I have been working so much I was able to save around 2k this month into my savings. On the bad side, I don’t have enough time to recheck my MCAT papers, nursing papers and programming lessons during the week. So, I slowed down academically a lot.
                    </p>
                    <p>
                    Got back into mountain biking seriously because I really want to get into racing until I turn 30 which means that I must start riding and training a lot. I am already planning to do swim/snowboarding during the winter in order to compensate or get myself a dirt jump and go indoor tricking.
                    </p>
                    <p>
                    School finally told us which classes where online and honestly, I am pleasantly surprised because most of them are online. I don’t know how I will manage online classes so for the next month I will force myself to learn some stuff during the week to simulate workload.
                    </p>
                    <h2>May 2020</h2>
                    <p>
                    At the beginning of this month I got a call from Decathlon that was looking for a bike mechanic to help them do some E-commerce with their bikes. Right now, the weather is getting hotter and people are starting to avoid public transits. Public transits with the current pandemic represent a breeding ground for COVID and in response people have started using more their personal means of transportation. Because the median salary is around 40k in Montreal you can see why people are opting for bikes. Biking represents a personal means of transportation that is reliable (unlike the goddamn STM in Montreal), it represents a healthy way of getting your daily dose of fitness during the day and finally its affordable for most people. With bikes ranging from 500$ to 10 000$ you can choose how much you want to invest in a bike.
                    </p>
                    <p>
                    Because of the explosion of demand in bikes I started working and realized that we had to verify, assemble and repair around  350 bikes per week for the next month basically. I was happy to get back to work, but to say the truth it is a daunting number even for the team I work with. At least I get to have a secure income for summer.  Since I am working 40-48h a week now I feel exhausted when I want to review MCAT material for next semester or learn coding.
                    </p>
                    <p>
                    I still want to learn how to use API, but I stumbled onto a small fear of mine. The gist of it is API keys are supposed to be personal because you can only use them around 10 times a minute. So, if you share it with somebody else well, you both can only use it 10 times a minute. I know how to do front end, so my API keys are going to be public. If someone uses mine without my approval well my website isn’t going to work. Some API charge you for every use and if someone steals it you can have a 6-digit receipt head your way very fast. In order to continue I need to see how to secure or encrypt my key to make sure my website works well.
                    </p>
                    <p>
                    Because I live alone now, I can’t really rely on someone else to make meals for me. I finally started using recipes and planning the budget I have in order to make sure I keep my spending in check. I want to save up a bit of money for my last semester so I can get through it without worrying about money. I do have to say with how cheap I am its looking like I can really save the amount I need ( 5k) easily.
                    </p>
                    <h2>April 2020</h2>
                    <p>
                    Because of the current pandemic I got a side job at our local grocery store just to have an income.  This month I learned a lot about photography, editing, filmmaking and coding. The reason I pushed forward with coding is because I want to learn how to use the React framework. If React is good enough for Facebook, then it’s good enough for me. I learned about photography because I want to start recording and editing my rides for YouTube on the side and take pictures for my website. On the downside I couldn’t review  Math and physics because I didn’t push hard enough on that.
                    </p>
                    <p>
                    I WAS FINALLY ABLE TO GET BACK ON MY BIKE! After such a long hiatus it was fun to get back on my spark 950 and continue teaching myself some tricks like manuals, endos, 180 and fakie.
                    I have yet to master those tricks but I plan to get them down this season.
                    </p>
                    <p>
                    Lesson of the Month: You can always find something to do.
                    </p>
                    <h2>March 2020</h2>
                    <p>
                    What a fun time to be alive. The highlight of this month was the coronavirus outbreak and the shift of tone in multiple countries regarding the severity of the disease. I was working until the 13 of March, then we got the announcement that work would be suspended until further notice. It’s the end of the month and we aren’t even sure if work is going to start again in April. In the meantime, I started biking, shifting my exercise to bodyweight exercise and staying home a lot more then I would want to. I am starting to get fluent in JS and I plan on learning the React.JS library so I can rework the appearance of my website and finally implement some JS. I have been playing more videogames, but I had fun creating Meme videos and pushing my editing skills forward. Most notably, my color grading skills and highlighting skills are getting way better. I can even switch colors in Adobe Photoshop.
                    </p>
                    <p>
                    Lesson of the Month: it’s hard to stay occupied home and it reminds me why I love working even if it is a 9 to 5. It gets me outside, and I can get out of my house.
                    </p>
                    <h2>February 2020</h2>
                    <p>
                    February was a bit dull for me. The only highlights that I had were the personal ones that I made for myself. I decided during this month that I was going to focus my training. Usually I bike and swim weekly, but with winter here I switch biking for the gym. When I swim, I try to hit around 20 laps in the 25-meter pool for a total of 1km ( 25m * 20 * 2 = 1000m). For some reason I wasn’t happy or exhausted with the process and the way I train. So, I decided to tailor my training around achieving 3 goals that allow me to build endurance and strength at the same time. Endurance wise I want to be able to achieve an ironman by the end of the year. That means that I should be able to bike 190km, swim 3.8km and run 42km. For strength my goal is to squat around 350lb or 158kg and bench around 250lb or 112kg. In order to achieve these goals, I had to rework my squatting technique because I wasn’t going low enough.
                    </p>
                    <p>
                    On the study side, I got contacted by UdeS that confirmed to me that they would allow me to transfer for my next semester if I feel like it. I decided to send them my academic dossier to talk with them and see what cursus they would make me do to get my degree in nursing. I was able to finish the CARS section of the MCAT and add a few tools to my test taking skills. On the coding side I am stuck on JavaScript and having a bit of difficulties in learning how to implement scripts on my website. Once I do expect this site to completely change. I feel like remodeling this site anyways to make it more dynamic in the future and revisit each page to assure responsiveness ( it’s a lot of work that I am giving myself but its going to help me build skills).
                    </p>
                    <p>
                    And that’s my February of 2020, dull but at least I got stuff to do to keep my brain going 😊.
                    </p>
                    <p>
                    <b>Lesson of the month:</b> I realised that planning and information gathering is a a crucial part for setting big goals for your life. Planning is easy, but information gathering on subjects that you didn't know much about before is tedious and can feel long. But, i guess that’s the price to pay if you want to set goals that can allow you to move further in life.
                    </p>
                    <h2>January 2020</h2>
                    <p>
                    To be honest my January of 2020 was bad. My nursing program is in an accelerated cursus. It’s a four-year program crammed into three years. They are aware of that and tell us students on the very first day how particular the nursing bachelor is compared to other programs. Because of that particularity, you cannot fail one class during a semester. If you fail one class, it puts you back a whole semester.
                    </p>
                    <p>
                    So, I failed a semester and it prolonged my bachelor to three and half years. I am currently on probation until the next cycle comes back. Because I am not enrolled this semester, I have a lot more time to learn skills that I was going to learn post-degree. Skills like coding, content creation and team management where things that I was interested in learning after my bachelors. But I decided to take on coding and review basic contents of biology and biochemistry to keep myself busy.
                    </p>
                    <p>
                    My goal for January was to publish this website online and have fun learning how to code. I had my own personal deadline but having someone like him and my dad put a bit more pressure on me is forcing me to concentrate more. Honestly, it’s helping me focus a bit because I know I have a duty to myself and to them to respect my deadline.
                    </p>
                    <p>
                    <b>Lesson of the month:</b> I currently find that the amount of pressure that I put on myself changes whether I do something for somebody or for myself. When I do something for myself, I know its not important because I am nonchalant guy. I owe to myself only what I want and to be honest I don’t want a lot. I think I am apathic and that for some reason I tend to ride with the waves, even if the waves are pushing me back to sea. When I do something for somebody else, I tend to put more effort. I want to give something perfect to them, so they are impressed or not able to formulate criticism. I like that I put a lot of effort when I do something for somebody, but I should also put all that effort when I do something for myself. Then, I think about all the work that it is going to take, and I start to procrastinate. I let work pile and I tend to mask myself with pointless pleasures like videogames and listening to music until I must do what is essential. Unfortunately, that work pattern never leaves me satisfied with my work, it just leaves me resentful of the task that I must do.
                    </p>
                </article>
            </div>    
        </div>
    )
}

export default Blog
